FROM openjdk:8
EXPOSE 9090
COPY target/employeeStatusManager-service-0.0.1-SNAPSHOT.jar employeeStatusManager-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","employeeStatusManager-service-0.0.1-SNAPSHOT.jar"]
